name: NK Auto Heartbeat

on:
schedule:
  - cron: '0,45 * * * *'
  workflow_dispatch:

permissions:
  contents: write   # ⭐ 必须加

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0   # ⭐ 必须
          token: ${{ secrets.GH_PAT }}

      - name: Update Heartbeat File
        run: |
          RAND_DELAY=$(( RANDOM % 300 + 1 ))
          echo "随机等待 $RAND_DELAY 秒..."
          sleep $RAND_DELAY

          RAND_ID=$(openssl rand -hex 2)
          export TZ='Asia/Shanghai'
          date > heartbeat.txt

          git config user.email "action@github.com"
          git config user.name "GitHub Action"

          git add heartbeat.txt
          git commit -m "Update NK-A service [ID: ${RAND_ID}] at $(date)" || echo "No changes"
          git push origin main
